# Generated by Django 5.2.8 on 2025-12-02 02:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='phone',
            new_name='phone_number',
        ),
    ]
