# Generated by Django 6.0 on 2025-12-11 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_favorite_productlike'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeroSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('subtitle', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('cta1_text', models.CharField(default='Shop Now', max_length=100)),
                ('cta1_link', models.CharField(default='/products', max_length=255)),
                ('cta2_text', models.CharField(blank=True, max_length=100)),
                ('cta2_link', models.CharField(blank=True, max_length=255)),
                ('background_image', models.ImageField(blank=True, null=True, upload_to='hero_slides/')),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='PromoBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('mobile_text', models.CharField(blank=True, max_length=100)),
                ('cta_text', models.CharField(default='Get Now', max_length=50)),
                ('cta_link', models.CharField(default='/products', max_length=255)),
                ('has_countdown', models.BooleanField(default=False)),
                ('countdown_hours', models.IntegerField(default=0)),
                ('countdown_minutes', models.IntegerField(default=0)),
                ('countdown_seconds', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='productlike',
            options={},
        ),
    ]
