# Generated by Django 6.0 on 2025-12-12 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_heroslide_promobanner_alter_productlike_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='heroslide',
            name='mobile_image',
            field=models.ImageField(blank=True, help_text='Optional: Different image for mobile screens', null=True, upload_to='hero_slides/'),
        ),
        migrations.AddField(
            model_name='heroslide',
            name='tablet_image',
            field=models.ImageField(blank=True, help_text='Optional: Different image for tablet screens', null=True, upload_to='hero_slides/'),
        ),
    ]
