# Generated by Django 6.0 on 2025-12-13 19:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_discountcode_order_discount_amount_order_subtotal_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReturnRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('defective', 'Defective/Damaged Item'), ('wrong_item', 'Wrong Item Received'), ('not_as_described', 'Not as Described'), ('changed_mind', 'Changed My Mind'), ('size_issue', 'Size/Color Issue'), ('quality_issue', 'Quality Issue'), ('other', 'Other')], max_length=50)),
                ('reason_description', models.TextField(help_text='Additional details about the return')),
                ('requested_refund_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Customer requested refund amount', max_digits=10, null=True)),
                ('approved_refund_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Admin approved refund amount', max_digits=10, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('refunded', 'Refunded'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('admin_notes', models.TextField(blank=True, help_text='Admin notes (internal)')),
                ('refund_reference', models.CharField(blank=True, help_text='Paystack refund reference', max_length=255, null=True)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='return_requests', to='store.order')),
                ('order_item', models.ForeignKey(blank=True, help_text='Specific item to return. If null, entire order return.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='return_requests', to='store.orderitem')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
